In [58]:
import numpy as np

# to see arguments of function go inside common brackets of func. and press Shift+Tab

In [17]:
a1 = np.array([1,2,3,6])
print(f" 1D array: {a1}, len: {len(a1)}, dimension: {a1.ndim}, type: {a1.dtype}, shape: {a1.shape}")

 1D array: [1 2 3 6], len: 4, dimension: 1, type: int32, shape: (4,)


In [18]:
a2 = np.array([[1.0, 2.7, 6.8], [8.5, 9.5, 55]])
print(f" 2D array: {a2}, len: {len(a2)}, dimension: {a2.ndim}, type: {a2.dtype}, shape: {a2.shape}")

 2D array: [[ 1.   2.7  6.8]
 [ 8.5  9.5 55. ]], len: 2, dimension: 2, type: float64, shape: (2, 3)


In [31]:
a3 = np.array([[['1', '2.7', '6.8'], ['8.5', '9.5', '55']],[['3','4','1'],['3','67','54']]])
print(f" 3D array: {a3}, len: {len(a3)}, dimension: {a3.ndim}, type: {a3.dtype}, shape: {a3.shape} \n")

print(f"max no. in a2 array is: {np.max(a2)}")

 3D array: [[['1' '2.7' '6.8']
  ['8.5' '9.5' '55']]

 [['3' '4' '1']
  ['3' '67' '54']]], len: 2, dimension: 3, type: <U3, shape: (2, 2, 3) 

max no. in a2 array is: 55.0


In [29]:
print(f"sum of elements in a2 is: {np.sum(a2)}")
print(f"sum of elements in a2 column is: {np.sum(a2, axis=0)}")
print(f"sum of elements in a2 row is: {np.sum(a2, axis=1)}")

sum of elements in a2 is: 83.5
sum of elements in a2 column is: [ 9.5 12.2 61.8]
sum of elements in a2 row is: [10.5 73. ]


In [34]:
a6 = np.array([[1,2,3,33,44],[4,5,6,11,22],[7,8,9,4,21],[56,34,10,11,12],[560,340,100,11,120],[506,304,100,101,102]])
print(a6)

[[  1   2   3  33  44]
 [  4   5   6  11  22]
 [  7   8   9   4  21]
 [ 56  34  10  11  12]
 [560 340 100  11 120]
 [506 304 100 101 102]]


In [35]:
print(a6[1:5,1:4])

[[  5   6  11]
 [  8   9   4]
 [ 34  10  11]
 [340 100  11]]


In [38]:
print(f"middle no is: {a6[2:3,2:3]}")

middle no is: [[9]]


In [40]:
print(f"last 4 no. of last row is: {a6[5:,1:]}")

last 4 no. of last row is: [[304 100 101 102]]


In [47]:
# to reshape a numpy array
# total elements in a2 is 6

a7 = a2.reshape(6,1)
print(f" reshaped column array is: {a7} \n")

a8 = a2.reshape(1,6)
print(f" reshaped row array is: {a8} \n")

a9 = a2.reshape(2,3,1)
print(f"reshaped 3D array is {a9}")

 reshaped column array is: [[ 1. ]
 [ 2.7]
 [ 6.8]
 [ 8.5]
 [ 9.5]
 [55. ]] 

 reshaped row array is: [[ 1.   2.7  6.8  8.5  9.5 55. ]] 

reshaped 3D array is [[[ 1. ]
  [ 2.7]
  [ 6.8]]

 [[ 8.5]
  [ 9.5]
  [55. ]]]


In [49]:
# change data type

a10 = a2.astype("str")
a10

array([['1.0', '2.7', '6.8'],
       ['8.5', '9.5', '55.0']], dtype='<U32')

In [55]:
# linspace
# 50 is total numbers to generate

a11 = np.linspace(1,10,50, retstep=True)
print(a11)

a13 = np.linspace(start=[1,2],stop=[9,10],num=9)
print(f"generate 2D array: {a13}")

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]), 0.1836734693877551)
generate 2D array: [[ 1.  2.]
 [ 2.  3.]
 [ 3.  4.]
 [ 4.  5.]
 [ 5.  6.]
 [ 6.  7.]
 [ 7.  8.]
 [ 8.  9.]
 [ 9. 10.]]


In [57]:
# np.arrange function
# here 3 represents difference between consecutuve terms

a12 = np.arange(1,100,3)
a12

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [61]:
# generate random numbers

np.random.randint(5, size=(1,6))

array([[4, 0, 4, 0, 4, 3]])

In [62]:
np.random.random(size=10)

array([0.81179341, 0.44554184, 0.87449008, 0.98601913, 0.30839941,
       0.53902224, 0.37338669, 0.4563225 , 0.37821895, 0.91652294])

In [64]:
a15 = np.random.uniform(low=5, high=20, size =100)
print(f"{a15}, len: {len(a15)}")

[19.68081517 19.3640396  16.73482955  8.87934103 15.38295654 18.0016782
  9.2679219  15.03141199  5.44945022 16.00087821 11.24105361 19.51152974
 14.95454243  7.62699094 17.63343515 11.06465545 10.66148342 10.93376003
 16.01241302 17.96350127 11.66574848 10.58016414 18.40728951 13.49174316
  9.09888481 18.65404875  7.07371334  8.86127251 15.97680461 18.05020856
 10.26083913 13.26676823  6.54804214 18.12498302  6.85481922 11.65557739
 12.53921433  8.49944838 12.59332544 17.49279866 18.71151057 17.55826551
 18.15589041 15.23592679 18.37127682 19.67985885 15.96033175 15.51251763
 16.50170351 17.34952989 16.07715165 18.91230304 16.62621976 13.08028007
 17.23104194 17.31300083 12.41425578 14.60472013 14.68401017 16.84133471
 19.99943955 11.09627164 10.38276224 11.73498756 18.9771376  19.08192143
 13.77312946 12.71514948  8.35680202  9.71509559 18.16930223 19.54656989
 10.88032806  9.73030349  7.3678389  13.41314327 15.06564299 11.65253066
  6.53508118  6.58038423 18.82468416 11.38489481 18.

In [ ]:
np.round()

In [72]:
# creating standard matrix

b1 = np.zeros((1,4), dtype = int)
b2 = np.ones((5,2), dtype = int)

b1,b2

(array([[0, 0, 0, 0]]),
 array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]))

In [76]:
# matrix multiplication

b3 = np.linspace(start = [1,2], stop = [5,7], num =5, dtype=int)
b3 = np.concatenate(b2, b3)

TypeError: only integer scalar arrays can be converted to a scalar index