# Code: U21EC019

## Basic Python Operations

In [1]:
a = 2
b = 10
c = "Hello World"
d = True

In [2]:
type(a)

int

In [3]:
type(c)

str

In [4]:
type(d)

bool

In [5]:
a + b

12

In [6]:
a - b

-8

In [7]:
a % b

2

In [8]:
a < b

True

In [9]:
a * c

'Hello WorldHello World'

In [10]:
c.upper()

'HELLO WORLD'

In [11]:
c.split('e')

['H', 'llo World']

## NumPy library

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3])

In [14]:
print(a)

[1 2 3]


In [15]:
b = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [16]:
print(b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [17]:
print(b[1,2]) #b[1][2]

23


In [18]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
np.linspace(1,9,10)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [25]:
np.random.rand()

0.9693227385772959

In [26]:
np.random.rand(5,5)

array([[0.20694951, 0.36291141, 0.48751171, 0.44446904, 0.22154617],
       [0.28304664, 0.36964692, 0.32234576, 0.66589287, 0.94575195],
       [0.42028927, 0.65882997, 0.79727153, 0.30276745, 0.89352658],
       [0.06746295, 0.70380953, 0.44328467, 0.86992603, 0.80999786],
       [0.68736704, 0.17564652, 0.99361178, 0.63915404, 0.43894313]])

In [27]:
np.random.randint(1,5)

1

In [28]:
np.random.randint(1,5,[5,5])

array([[1, 3, 2, 1, 1],
       [1, 1, 1, 2, 4],
       [2, 1, 3, 1, 4],
       [1, 1, 2, 3, 2],
       [1, 1, 1, 3, 3]])

In [29]:
a = np.random.randn(5,5)
a

array([[ 2.15707861,  0.172946  ,  0.51052851,  0.38308835, -0.24706569],
       [ 0.46514289,  1.15208687, -0.00759869, -2.41221891, -1.54402136],
       [ 0.83789871, -0.07650936, -0.44780535, -0.43510907,  1.83711762],
       [ 1.57741775,  1.52473935,  1.50167717, -1.37672331, -0.58083952],
       [-1.62914399, -0.62929375,  0.10838818,  0.4501332 , -0.80231506]])

In [30]:
a>0

array([[ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False,  True,  True, False]])

In [31]:
a[a>0]=10
a

array([[ 1.00000000e+01,  1.00000000e+01,  1.00000000e+01,
         1.00000000e+01, -2.47065690e-01],
       [ 1.00000000e+01,  1.00000000e+01, -7.59868845e-03,
        -2.41221891e+00, -1.54402136e+00],
       [ 1.00000000e+01, -7.65093583e-02, -4.47805352e-01,
        -4.35109071e-01,  1.00000000e+01],
       [ 1.00000000e+01,  1.00000000e+01,  1.00000000e+01,
        -1.37672331e+00, -5.80839518e-01],
       [-1.62914399e+00, -6.29293747e-01,  1.00000000e+01,
         1.00000000e+01, -8.02315063e-01]])

## Array Method

In [32]:
data = [1,3,5,2]
arr = np.array(data)
print(arr)
print(arr.dtype)
print(arr.shape)

[1 3 5 2]
int32
(4,)


In [33]:
a = np.random.rand(1000)

In [34]:
a.min()

0.0010315460215860606

In [35]:
a.max()

0.9986860070107748

In [36]:
a.mean()

0.5017030156352815

In [37]:
c = np.random.rand(4)

In [38]:
c

array([0.53236795, 0.65369546, 0.68970321, 0.89697053])

In [39]:
c.argmin()

0

In [40]:
c.argmax()

3

In [41]:
d = c.reshape(2,2)
print(d.shape)
d

(2, 2)


array([[0.53236795, 0.65369546],
       [0.68970321, 0.89697053]])

In [42]:
c.reshape(4)

array([0.53236795, 0.65369546, 0.68970321, 0.89697053])

In [43]:
c.reshape(2,2)

array([[0.53236795, 0.65369546],
       [0.68970321, 0.89697053]])

In [44]:
c.flatten()

array([0.53236795, 0.65369546, 0.68970321, 0.89697053])

In [45]:
e = np.array([0])

In [46]:
f = np.array([0.])

In [47]:
e.dtype

dtype('int32')

In [48]:
f.dtype

dtype('float64')

## Functions

In [49]:
a = np.arange(0,1,0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [50]:
np.square(a)

array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81])

In [51]:
np.sin(a)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

In [52]:
np.exp(a)

array([1.        , 1.10517092, 1.22140276, 1.34985881, 1.4918247 ,
       1.64872127, 1.8221188 , 2.01375271, 2.22554093, 2.45960311])

## Linear Algebra

In [53]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [54]:
C = np.dot(A, B)
# Or equivalently: C = A @ B

In [55]:
print(C)

[[19 22]
 [43 50]]


In [56]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [57]:
# Define a matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
# Compute SVD
U, S, V = np.linalg.svd(A)
print("U:")
print(U)
print("\nS:")
print(S)
print("\nV:")
print(V)

U:
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

S:
[9.508032   0.77286964]

V:
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
